---

- name: queue service clustered
  hosts: all
  become: true
  tasks:
    - include_role:
        name: stone-payments.disk-manager
      tags: config-disk-manager
      vars:
        diskmanager_management_lvm: true
        diskmanager_lvm_configs:
          - pvs_name: '/dev/sdb'
            vg_name: rmqvg
            lv_name: rmq
            lv_size: +100%FREE
            fstype: ext4
            shrink: false
            resizefs: true
            mount: true
            mount_point_path: /var/lib/rabbitmq
            mount_point_owner: root
            mount_point_group: root
            mount_point_opts: defaults
            state: present

    - include_role:
        name: ansible-rabbitmq
      tags: [ rabbitmq_configuration, rabbitmq_monitoring ]
      vars:
        rabbitmq_clustering_enabled: true
        rabbitmq_clustering_cluster_name: "payments-rmq"
        rabbitmq_repository_on_satellite:
          - Stone_RabbitMQ_erlang_rhel7
          - Stone_RabbitMQ_38_rhel7
        rabbitmq_system_number_open_files: 499000
        rabbitmq_conf_disk_free_limit_mem_relative: 1.2
        rabbitmq_conf_vm_memory_high_watermark: 0.7
        rabbitmq_conf_num_acceptors_tcp: 100
        rabbitmq_newrelic_agent_enabled: true
        rabbitmq_newrelic_cluster_name: {{ rabbitmq_clustering_cluster_name }}
        rabbitmq_newrelic_labels:
          env: test-payments-clustered
          role: rabbitmq
