---
- name: set random erlang cookie
  set_fact:
    rabbitmq_erlang_cookie: "{{ lookup('password', '/dev/null length=15 chars=ascii_uppercase,digits') }}"
  run_once: true
  delegate_to: ansible_play_hosts_all[0]
  when: rabbitmq_erlang_cookie is undefined

- block:
  - name: copy erlang cookie
    template:
      src: erlang.cookie.j2
      dest: "{{ rabbitmq_erlang_cookie_file_path }}"
      owner: rabbitmq
      group: rabbitmq
      mode: 0400
      backup: yes

  - name: restart rabbitmq server
    service:
      name: rabbitmq-server
      state: restarted

  - name: stop rabbitmq app
    command: rabbitmqctl stop_app
    when: "inventory_hostname != ansible_play_hosts_all[0]"

  - name: join rabbitmq cluster
    command: rabbitmqctl join_cluster "rabbit@{{ ansible_play_hosts_all[0] }}"
    register: cluster_joined
    when: "inventory_hostname != ansible_play_hosts_all[0]"
    retries: 2
    delay: 5

  - name: start rabbitmq app
    command: rabbitmqctl start_app
    when: "inventory_hostname != ansible_play_hosts_all[0]"

  when:
    - rabbitmq_clustering_enabled

