---
- name: set random erlang cookie
  set_fact:
    rabbitmq_erlang_cookie: "{{ lookup('password', '/dev/null length=15 chars=ascii_uppercase,digits') }}"
  run_once: true
  delegate_to: ansible_play_hosts_all[0]
  when: rabbitmq_erlang_cookie is undefined

- block:
  - name: force longnames when rabbit is in cluster
    set_fact:
      rabbitmq_conf_env: "{{ rabbitmq_conf_env | default([]) }} + {{ [ USE_LONGNAME: 'true'] }}"

  - debug: var=rabbitmq_conf_env

  - name: copy erlang cookie
    template:
      src: erlang.cookie.j2
      dest: "{{ rabbitmq_erlang_cookie_file_path }}"
      owner: rabbitmq
      group: rabbitmq
      mode: 0400
      backup: yes

  - name: restart rabbitmq server
    service:
      name: rabbitmq-server
      state: restarted

  - name: stop rabbitmq app
    command: rabbitmqctl stop_app
    when: "inventory_hostname != ansible_play_hosts_all[0]"

  - name: join rabbitmq cluster
    command: rabbitmqctl join_cluster "rabbit@{{ ansible_play_hosts_all[0] }}"
    register: cluster_joined
    when: "inventory_hostname != ansible_play_hosts_all[0]"
    retries: 2
    delay: 5

  - name: start rabbitmq app
    command: rabbitmqctl start_app
    when: "inventory_hostname != ansible_play_hosts_all[0]"

  when:
    - rabbitmq_clustering_enabled

## In cluster environments, only one node should use the all command; the rest should use the inventory command.
## ref: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration#config
- name: force newrelic rabbitmq agent command as inventory
  set_fact:
    rabbitmq_newrelic_command: inventory
  when: "inventory_hostname != ansible_play_hosts_all[0]"
