---

- name: copy the rabbitmq configuration file
  template:
    src=rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
    owner=root
    group=rabbitmq
    mode=0644
    backup=yes
  notify: rabbitmq restart
