---
- name: change enabled_plugins file permissions
  file:
    state=touch
    path={{ rabbitmq_enabled_plugins_file_path }}
    owner={{ rabbitmq_enabled_plugins_file_owner }}
    group={{ rabbitmq_enabled_plugins_file_group }}
    mode={{ rabbitmq_enabled_plugins_file_mode }}
  changed_when: false

- name: copy the rabbitmq configuration file
  template:
    src=rabbitmq.config.j2
    dest={{ rabbitmq_config_file_path }}
    owner={{ rabbitmq_config_file_owner }}
    group={{ rabbitmq_config_file_group }}
    mode={{ rabbitmq_config_file_mode }}
    backup=yes

- name: generate rabbitmq environment-variables file
  template:
    src=rabbitmq-env.conf.j2
    dest={{ rabbitmq_env_variables_file_path }}
    owner={{ rabbitmq_config_file_owner }}
    group={{ rabbitmq_config_file_group }}
    mode={{ rabbitmq_config_file_mode }}
    backup=yes
  when: rabbitmq_conf_env is defined

- name: ensure rabbitmq server is running
  service:
    name: rabbitmq-server
    state: started

- name: ensure the users are removed
  rabbitmq_user:
    user={{ item }}
    state=absent
  with_items: "{{ rabbitmq_users_remove }}"

- name: ensure users exist
  rabbitmq_user:
    user={{ item }}
    password={{ item }}
    tags={{ rabbitmq_administrator_tag }}
    state=present
  with_items: "{{ rabbitmq_users }}"
