---
- name: Subscribe to puppet repository on satellite.
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ rabbitmq_repository_on_satellite }}"
  when: rabbitmq_repository_on_satellite is defined

- block:
  - name: add package-cloud rabbitmq-erlang rpm key
    rpm_key:
      key: https://packagecloud.io/rabbitmq/erlang/gpgkey
      state: present

  - name: add package-cloud rabbitmq-server rpm key
    rpm_key:
      key: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
      state: present

  - name: add package-cloud rabbitmq-erlang repo
    yum_repository:
        name: rabbitmq_erlang
        enabled: yes
        repo_gpgcheck: yes
        sslverify: yes
        gpgkey: https://packagecloud.io/rabbitmq/erlang/gpgkey
        state: present
        gpgcheck: no
        metadata_expire: 300
        baseurl: https://packagecloud.io/rabbitmq/erlang/el/$releasever/$basearch
        description: RabbitMQ-Erlang Repo

  - name: add package-cloud rabbitmq-server repo
    yum_repository:
        name: rabbitmq_rabbitmq-server
        enabled: yes
        repo_gpgcheck: yes
        sslverify: yes
        gpgkey: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present
        gpgcheck: no
        metadata_expire: 300
        baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/$releasever/$basearch
        description: RabbitMQ-Server Repo
  when: rabbitmq_repository_on_satellite is undefined

- name: install rabbitmq-server dependencies (RedHat)
  package:
    name: ['libselinux-python']
    state: present

- name: install rabbitmq-server {{ rabbitmq_version }}
  package:
    name: "rabbitmq-server-{{ rabbitmq_package }}.el7.noarch"
    state: present

- name: enable rabbitmq-server to survive reboot
  service:
    name: rabbitmq-server
    enabled: yes
