---
- name: install rabbitmq-server dependencies (RedHat)
  yum: name="{{ item }}" state=present
  with_items:
    - erlang
    - libselinux-python

- name: install rabbitmq-server {{ rabbitmq_version }} (RedHat)
  yum: name=rabbitmq-server-{{ rabbitmq_version }} state=present

- name: enable rabbitmq-server to survive reboot
  service:
    name: rabbitmq-server
    enabled: yes
