---
- name: Install RabbitMQ on {{ ansible_distribution }}
  include_tasks: "{{ rabbitmq_install_task }}"
  when: rabbitmq_install_enabled
  vars:
    rabbitmq_install_task: "install.{{ (ansible_os_family | lower) if (ansible_os_family == 'RedHat') else (ansible_distribution | lower) }}.yml"
  tags: rabbitmq_install

- name: Configure RabbitMQ service
  include_tasks: configuration.yml
  tags: rabbitmq_configuration

- name: Install plugins
  include_tasks: plugins.yml
  tags: rabbitmq_plugins

- name: Configure cluster
  include_tasks: clustering.yml
  when: rabbitmq_clustering_enabled
  tags: rabbitmq_clustering

- name: Configure new-relic rabbitmq infra agent
  include_tasks: monitoring-newrelic.yml
  when: rabbitmq_newrelic_agent_enabled
  tags: rabbitmq_monitoring
