---
- block:
  - set_fact:
      newrelic_license: "{{ lookup('env', 'NEWRELIC_LICENSE_KEY') | default(omit, true) }}"

  - name: check if license key is defined
    assert:
      that:
        - newrelic_license is defined

  - name: Install and activate new-relic infra agent and rabbitmq agent
    include_role:
      name: newrelic.infrastructure-agent
    vars:
      nrinfragent_config:
        license_key: "{{ newrelic_license }}"
        log_file: "/var/log/newrelic-infra/nr-infra.log"
      nrinfragent_integrations:
        - name: nri-rabbitmq
          state: "latest"

  - name: set newrelic filters
    set_fact:
      rabbitmq_filters:
        queues: "{{ rabbitmq_newrelic_queues | default(omit, true) }}"
        exchanges: "{{ rabbitmq_newrelic_exchanges | default(omit, true) }}"
        vhosts: "{{ rabbitmq_newrelic_vhosts | default(omit, true) }}"
        queues_regexes: "{{ rabbitmq_newrelic_queues | ternary(omit, '[\".*\"]', '[\".*\"]') }}"
        exchanges_regexes: "{{ rabbitmq_newrelic_exchanges | ternary(omit, '[\".*\"]', '[\".*\"]') }}"
        vhosts_regexes: "{{ rabbitmq_newrelic_vhosts | ternary(omit, '[\".*\"]', '[\".*\"]') }}"

  ## In cluster environments, only one node should use the all command; the rest should use the inventory command.
  ## ref: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration#config
  - name: force newrelic rabbitmq agent command as inventory
    set_fact:
      rabbitmq_newrelic_command: "inventory"
    when:
      - rabbitmq_clustering_enabled is defined
      - rabbitmq_clustering_enabled
      - "inventory_hostname != ansible_play_hosts[0]"

  - name: ensure monitoring user exists
    rabbitmq_users:
      user={{ rabbitmq_newrelic_username }}
      password={{ rabbitmq_newrelic_password }}
      tags={{ rabbitmq_administrator_tag }}
      read_priv=.*
      state=present

  - name: configure nri-rabbitmq
    template:
      src=newrelic-rabbitmq-config.yml.j2
      dest={{ rabbitmq_newrelic_agent_config_file_path }}
      backup=yes

  tags: rabbitmq_monitoring
