---

- name: symlink rabbitmq bin to sbin
  file:
    src={{ rabbitmq_bin_path }}
    dest={{ rabbitmq_sbin_path }}
    state=link

- name: enable plugins
  rabbitmq_plugin:
    names={{ rabbitmq_plugins | join(',') }}
  notify: rabbitmq restart

- name: force plugins file permissions
  file:
    state=file
    path={{ rabbitmq_enabled_plugins_file_path }}
    owner={{ rabbitmq_enabled_plugins_file_owner }}
    group={{ rabbitmq_enabled_plugins_file_group }}
    mode={{ rabbitmq_enabled_plugins_file_mode }}
