---
- name: Check if cluster has to be enabled and cluster_name is defined
  assert:
    that:
      - rabbitmq_clustering_enabled
      - rabbitmq_clustering_cluster_name | default('', true) | length > 4
    fail_msg: "When using cluster a cluster_name must be set with at least 5 chars"
  run_once: true

- name: Set dynamic group name
  set_fact:
    cluster_group_name: "rmq_cluster_{{ rabbitmq_clustering_cluster_name }}"
  run_once: true

- name: Set dynamic group based on cluster_name
  group_by:
    key: "{{ cluster_group_name }}"
  run_once: true

- name: Show the name of master node
  debug:
    msg: "{{ groups[cluster_group_name][0] }}"
    verbosity: 2
  run_once: true

- name: Set random erlang cookie
  set_fact:
    rabbitmq_erlang_cookie: "{{ lookup('password', '/dev/null length=15 chars=ascii_uppercase,digits') }}"
  run_once: true
  delegate_to: "{{ groups[cluster_group_name][0] }}"
  when: (rabbitmq_erlang_cookie is undefined) or (rabbitmq_erlang_cookie | default(None, true) == None)

- name: Copy erlang cookie
  template:
    src: erlang.cookie.j2
    dest: "{{ rabbitmq_erlang_cookie_file_path }}"
    owner: rabbitmq
    group: rabbitmq
    mode: "0400"
    backup: true
  notify: restart rabbitmq

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Check RabbitMQ is running in cluster mode
  command: rabbitmqctl cluster_status --formatter json
  delegate_to: "{{ groups[cluster_group_name][0] }}"
  run_once: true
  changed_when: false
  register: rabbitmq_cluster_status

- name: Set rabbitmq_cluster_running_nodes fact
  set_fact:
    rabbitmq_cluster_status: "{{ rabbitmq_cluster_status.stdout | from_json }}"
  run_once: true

- name: Task block to clear new nodes before joining to cluster
  block:
    - name: Stop rabbitmq app
      command: rabbitmqctl stop_app

    - name: Reset rabbitmq before entering cluster
      command: rabbitmqctl force_reset

    - name: Force forget cluster node on 'master'
      command: "rabbitmqctl forget_cluster_node {{ rabbitmq_node }}"
      delegate_to: "{{ groups[cluster_group_name][0] }}"
      ignore_errors: true

    - name: Join rabbitmq cluster
      command: rabbitmqctl join_cluster "rabbit@{{ groups[cluster_group_name][0] }}"
      register: cluster_joined
      retries: 2
      delay: 5

    - name: Start rabbitmq app
      command: rabbitmqctl start_app
  vars:
    rabbitmq_node: "rabbit@{{ ansible_nodename }}"
  when:
    - ansible_nodename != groups[cluster_group_name][0]
    - (rabbitmq_node not in rabbitmq_cluster_status['running_nodes']) or (rabbitmq_clustering_force)

- name: Set rabbitmq cluster name
  rabbitmq_global_parameter:
    name: cluster_name
    value: "{{ rabbitmq_clustering_cluster_name | to_json }}"
    state: present
