---
- name: Set random erlang cookie
  set_fact:
    rabbitmq_erlang_cookie: "{{ lookup('password', '/dev/null length=15 chars=ascii_uppercase,digits') }}"
  run_once: true
  delegate_to: "{{ rabbitmq_master_node }}"
  when: rabbitmq_erlang_cookie | lenth > 0

- name: Copy erlang cookie
  template:
    src: erlang.cookie.j2
    dest: "{{ rabbitmq_erlang_cookie_file_path }}"
    owner: rabbitmq
    group: rabbitmq
    mode: "0400"
    backup: true
  notify: restart rabbitmq

- block:
    - name: Stop rabbitmq app
      command: rabbitmqctl stop_app

    - name: Reset rabbitmq before entering cluster
      command: rabbitmqctl reset

    - name: Force forget cluster node on 'master'
      command: "rabbitmqctl forget_cluster_node rabbit@{{ inventory_hostname }}"
      delegate_to: "{{ rabbitmq_master_node }}"
      ignore_errors: true

    - name: Join rabbitmq cluster
      command: rabbitmqctl join_cluster "rabbit@{{ rabbitmq_master_node }}"
      register: cluster_joined
      retries: 2
      delay: 5
      ignore_errors: true

    - name: Start rabbitmq app
      command: rabbitmqctl start_app
  when: inventory_hostname != rabbitmq_master_node

- name: Set rabbitmq cluster name
  rabbitmq_global_parameter:
    name: cluster_name
    value: "{{ rabbitmq_clustering_cluster_name | to_json }}"
    state: present
  when:
    - rabbitmq_clustering_cluster_name | length > 0
    - rabbitmq_clustering_cluster_name | default(None, true) != None
