---

- name: rabbitmq restart
  service:
    name: rabbitmq-server
    state: restarted

- name: start rabbitmq app
  command: rabbitmqctl start_app

- name: restart newrelic-infra
  service:
    name: newrelic-infra
    state: restarted