---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: yamllint-config.yaml
platforms:
  - name: non-clustered
    box: centos/7
    provider_name: virtualbox
    provider_memory: 512
    provider_cpus: 1
    ansible_groups:
        - group1
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 15672, host: 15672"
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenatio:
  name: default
verifier:
  name: testinfra
  directory: ../../tests/default
  lint:
    name: flake8
